apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - image: redis:7-alpine
          imagePullPolicy: IfNotPresent
          name: redis
          command:
            - redis-server
            - --requirepass $(REDIS_PASS)

          ports:
            - containerPort: 6379
              name: redis
